apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-gateway
  labels:
    app: expressjs-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: expressjs-gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expressjs-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: subnet
                operator: In
                values:
                - public
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - normal
      containers:
      - image: CONTAINER_IMAGE
        name: expressjs-gateway
        env:
          - name: BACKEND_URL
            value: expressjs-app-red.default.svc.cluster.local
        ports:
        - containerPort: 3001
          protocol: TCP